services:
  survey-api-dev:
    build:
      context: ./api
      dockerfile: Dockerfile # Your existing api/Dockerfile
    container_name: survey_api_dev
    volumes:
      - ./api/app:/root/app
    environment:
      - MONGO_URL=mongodb://mongodb-dev:27017
      - SESSION_SECRET_KEY=a_dev_secret_key_for_sessions
    depends_on:
      - mongodb-dev
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: unless-stopped

  survey-ui-dev:
    image: node:slim # Using a generic Node image for simplicity
    container_name: survey_ui_dev
    working_dir: /ui
    volumes:
      - ./ui:/ui # Mount your local UI code
      - /ui/node_modules # Anonymous volume for node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      # VITE_API_DIRECT_URL is NOT set here, so apiClient.ts will use relative paths for Nginx
    command: >
      sh -c "if [ ! -d "node_modules" ] || [ ! -f "node_modules/.vite/deps/manifest.json" ]; then npm install; fi &&
             npm run dev -- --host --port 5173"
    restart: unless-stopped

  nginx-dev:
    image: nginx:alpine
    container_name: nginx_dev_proxy
    ports:
      - "80:80"
    volumes:
      - ./ui/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro # Dev Nginx config
    depends_on:
      - survey-api-dev
      - survey-ui-dev
    restart: unless-stopped

  mongodb-dev:
    image: mongo:latest
    container_name: mongodb_dev_container
    ports:
      - "27018:27017" # Host port 27018 to avoid conflict with potential local mongo on 27017
    volumes:
      - mongodb_dev_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_dev_data:
