# docker-compose.dev.yml
services:
  survey_api_dev:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: survey_api_dev
    volumes:
      - ./api:/root 
    working_dir: /root 
    environment:
      - MONGO_URL=mongodb://mongodb_dev_container:27017 # CORRECTED: Match service name
      - DATABASE_NAME=survey_db_dev 
      - SESSION_SECRET_KEY=a_dev_secret_key_for_sessions
      - DEV_UI_HOST_PORT_VITE=5174 # For CORS settings.py
      - DEV_NGINX_PROXY_HOST_PORT=8080 # For CORS settings.py
    ports: 
      - "8001:8000" 
    depends_on:
      - mongodb_dev_container # CORRECTED: Match service name
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "/root/app"]
    restart: unless-stopped
    stop_grace_period: 0s

  survey_ui_dev:
    image: node:22-slim 
    container_name: survey_ui_dev
    working_dir: /ui
    volumes:
      - ./ui:/ui 
      - /ui/node_modules 
    environment:
      - CHOKIDAR_USEPOLLING=true
      # - VITE_API_DIRECT_URL=http://localhost:8001 # Uncomment if UI needs to hit API directly, not via nginx_dev
    ports:
      - "5174:5173" 
    command: >
      sh -c "if [ ! -d 'node_modules' ] || [ ! -f 'node_modules/.vite/deps/_metadata.json' ]; then npm install; fi && 
             npm run dev -- --host 0.0.0.0 --port 5173"
    restart: unless-stopped
    stop_grace_period: 0s

  nginx_dev: 
    image: nginx:alpine
    container_name: nginx_dev # Kept as per your file
    ports:
      - "8080:80" 
    volumes:
      - ./ui/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - survey_api_dev
      - survey_ui_dev
    restart: unless-stopped
    stop_grace_period: 0s

  mongodb_dev_container: # Kept name as per your file
    image: mongo:latest
    container_name: mongodb_dev_container
    ports:
      - "127.0.0.1:27018:27017" 
    volumes:
      - mongodb_dev_data:/data/db
    restart: unless-stopped
    stop_grace_period: 0s

volumes:
  mongodb_dev_data: